//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by GitVersion.
//
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("1.3.5.0")]
[assembly: AssemblyVersion("1.3.5.0")]
[assembly: AssemblyInformationalVersion("1.3.5-newkeyvaultlib.0+Branch.feature-newkeyvaultlib.Sha.6f03c36c3c4a006203856d21659652d55a24ebd5")]
